import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent, SetStateAction, useState } from 'react'
import styled from 'styled-components'
import { Header } from '../src/components/header'
import React,{useContext} from 'react';
import { UseContext } from '../src/provider/UseProvider'

type Context = {
    categories: Array<string>,
  favorite: Array<string>,
      setCategory: (category: SetStateAction<string[]>) => void,
  setFavorite: (favorite: SetStateAction<string[]>) => void,
}

const Home: NextPage = () => {
  const context:Context= useContext(UseContext);
  const { categories, favorite,setCategory,setFavorite } = context;
  const [text, setText] = useState('')
  const onChangeText = (e: ChangeEvent<HTMLInputElement>) => setText(e.target.value);
  const onClickAdd = () => {
    const category = [...categories];
    category.push(text);
    setCategory(category);
    setText('');
    alert(`${text}を今日観るに追加しました。`);
  }
  const onClickFavoriteAdd = () => {
    const favo=[...favorite]
    favo.push(text);
    setFavorite(favo);
    alert(`${text}をお気に入りに追加しました。`)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SCard>
        <SInput type="text" value={text} onChange={onChangeText} placeholder='観たい動画のキーワードを入力してください' />
        <p style={{textAlign:'center',marginBottom:'5px',borderTop:'1px solid #ddd',width:'80%',marginRight:'auto',marginLeft:'auto',paddingTop:'15px'}}>今日観るリスト</p>
        <SList>
              {categories.map((category,id) => (
                <SItem key={id } style={{color:'black',margin:'auto',width:'fit-content'} }>{category}</SItem>
              ))}
          </SList>
      <SButton onClick={onClickAdd} disabled={text===''?true:false}>
        今日観るに追加
      </SButton>
      <SButton onClick={onClickFavoriteAdd} disabled={text===''?true:false}>
        お気に入りに追加
      </SButton>
      </SCard>
      <Header />
    </div>
  )
}

export default Home

const SInput = styled.input`
display:block;
margin: 0 auto 10px;
width: 75%;
padding:20px 15px;
line-height:1;
border-radius:100px;
border:1px solid #ddd;
&::after{
  content:"";
  display:block;
}
`

const SCard = styled.div`
margin:auto;
margin-top:15vh;
padding-top:50px;
  width: 90%;
  height: 50vh;
  box-shadow: 0px 0px 15px -5px #777777;
border-radius: 10px;
`
const SButton= styled.button`
display:block;
width:80%;
border-radius:12px;
background-color:#000;
color:#fff;
padding:20px 0;
margin:30px auto;
cursor:pointer;
transition:.3s;
&:hover{
  opacity:.8;
}
`
const SItem = styled.li`
margin-bottom:5px;
`
const SList=styled.ul`
  list-style-type:none;
  margin: 0 auto;
  padding-left:0;
  padding-bottom:12px;
  width:80%;
  border-bottom:1px solid #ddd;
`